modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile= "Icon.png"
authors = "Rarin"
description = "adds colored variants of pipes & tanks for Create"

[[mixins]]
config="ColorfulPipes.mixins.json"

[[dependencies."${mod_id}"]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create_connected"
type="optional"
versionRange="[1.2.0-mc1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create_dragons_plus"
type="optional"
versionRange="[1.10.1,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create_enchantment_industry"
type="optional"
versionRange="[2.3.1,)"
ordering="NONE"
side="BOTH"

